fixes

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -56,13 +56,20 @@ jobs:
       run: |
           echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-33;google_apis;arm64-v8a"
           echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd --force --name TestEmulator --abi google_apis/arm64-v8a --package 'system-images;android-33;google_apis;arm64-v8a'
-          $ANDROID_HOME/emulator/emulator -avd TestEmulator -no-window -no-audio -gpu swiftshader_indirect -accel-check &
+
+          $ANDROID_HOME/emulator/emulator -avd TestEmulator -no-window -no-audio -gpu swiftshader_indirect -accel on &
           $ANDROID_HOME/platform-tools/adb wait-for-device
           boot_completed=""
-          until [[ "$boot_completed" == "1" ]]; do
+          timeout=0
+          until [[ "$boot_completed" == "1" ]] || [[ $timeout -ge 60 ]]; do
             sleep 5
             boot_completed=$($ANDROID_HOME/platform-tools/adb shell getprop sys.boot_completed | tr -d '\r')
-            echo "Waiting for emulator boot to complete..."
+            timeout=$((timeout+1))
+            echo "Waiting for emulator boot... attempt: $timeout"
           done
+          if [[ "$boot_completed" != "1" ]]; then
+            echo "Emulator boot failed or took too long!"
+            exit 1
+          fi
           echo "Emulator booted successfully!"
     - run: npm run test:android-ci
